try {
    throw Error('Error')
} catch (error) {
    log(error)
}
