try {
    throw error('Error')
} catch (e) {
    log(e)
}
