try {
    throw error('Error')
} catch (error) {
    log(error)
}
